run:
  timeout: 2m
  build-tags:
    - bacgo

linters-settings:
  cyclop:
    max-complexity: 15
  funlen:
    lines: 100
    statements: 40

linters:
  enable-all: true
  disable:
    - wrapcheck
    - paralleltest
    - err113
    - mnd
    - exhaustruct
    - interfacebloat
    - depguard
    - godox
    - maintidx
    - gomnd
# Deprecated
    - exportloopref
    - execinquery


issues:
  exclude-use-default: false
  exclude-rules:
    - path: .*_test\.go
      linters:
        - funlen
        - lll
        - dupl
        - goconst
        - noctx
        - wsl

severity:
  default-severity: error
  rules:
    - linters:
      - godox
      severity: info
