// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: android.sql

package sqlc

import (
	"context"
)

const populateAndroidMetadata = `-- name: PopulateAndroidMetadata :exec
INSERT INTO android_metadata(locale) VALUES (?)
`

func (q *Queries) PopulateAndroidMetadata(ctx context.Context, locale string) error {
	_, err := q.db.ExecContext(ctx, populateAndroidMetadata, locale)
	return err
}
