// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

type AndroidMetadatum struct {
	Locale string
}

type Metadatum struct {
	Name  string
	Value string
}

type Tile struct {
	ZoomLevel  uint64
	TileColumn uint64
	TileRow    uint64
	TileData   []byte
}
